spring.application.name=AkttAPI-Springed
spring.datasource.url=jdbc:postgresql://ep-frosty-field-ag18tqqa.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=16311
jwt.secret=${JWT_SECRET}
